# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oneshot < Formula
  desc "A first first-come-first-serve, single-fire, feature-rich HTTP server. Easily transfer files to and from your terminal and any browser or HTTP client."
  homepage "https://www.oneshot.uno"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/forestnode-io/oneshot/releases/download/v2.0.0/oneshot_Darwin_x86_64.tar.gz"
      sha256 "5d2a381f964cd14c7ace1551f75a1c324d914244586836fcf050e795de11935e"

      def install
        bin.install "oneshot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/forestnode-io/oneshot/releases/download/v2.0.0/oneshot_Darwin_arm64.tar.gz"
      sha256 "07f839d6c6abba3a0f15d2b38cf420b97f63afd08e13c3b187b8b146adad166b"

      def install
        bin.install "oneshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/forestnode-io/oneshot/releases/download/v2.0.0/oneshot_Linux_x86_64.tar.gz"
      sha256 "29da05438dbd0d483963d9dc9f14398cdceb0e15d5fae37d3b6b94407292d4d0"

      def install
        bin.install "oneshot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/forestnode-io/oneshot/releases/download/v2.0.0/oneshot_Linux_arm64.tar.gz"
      sha256 "9f0a3b2d3a46f4697979669988199753cdaffcf050b64883f2c126ca0c617661"

      def install
        bin.install "oneshot"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/forestnode-io/oneshot/releases/download/v2.0.0/oneshot_Linux_armv6.tar.gz"
      sha256 "758783abe8614fc8d3666d5f2d67ef82146cf3a91b648d621ac9738b92ff5627"

      def install
        bin.install "oneshot"
      end
    end
  end

  test do
    system "#{bin}/oneshot", "version"
  end
end
